version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: boris
      MONGO_INITDB_ROOT_PASSWORD: passb
    volumes:
      - /databases/mongodb/findyourbook/db:/data/db
    ports:
      - 27017:27017