server:
    port: 8080


spring:
    jackson:
        date-format: space.borisgk.findyourbookelastic.api.invoker.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false

springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

management:
  endpoint:
    prometheus:
      enabled: true
