server:
    port: 8080


spring:
  jackson:
        date-format: space.borisgk.findyourbookelastic.api.invoker.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
  data:
    elasticsearch:
      repositories:
        enabled: true

findyourbook:
  elastic:
    host: ${ELASTIC_HOST:localhost:9200}
    password: ${ELASTIC_PASS:}
    username: ${ELASTIC_USERNAME:}

springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

management:
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
    tracer: TRACE